### PR TITLE
Fix startup activation to use correct variable.

### PR DESCRIPTION
**Pull request by Hvalfisk**

### CODE REVIEW

**Review by dbarsam — COMMENTED** [review]
How is `rainbow_activate` more correct than `rainbow_active`?

**Comment by Hvalfisk** [comment]
`rainbow_activate` is the variable that is set to enable or disable the plugin at startup (to activate it or not). `rainbow_active` stores the current activity-state of the plugin, whether it is currently active or not, to facility the toggling of the plugin.   

In [plugin/rainbow.vim](https://github.com/dbarsam/vim-rainbow-parentheses/blob/master/plugin/rainbow.vim), you have:
```
if exists("g:rainbow_active") && g:rainbow_active
	call rainbow#toggle()
endif
```
And in [autoload/rainbow.vim](https://github.com/dbarsam/vim-rainbow-parentheses/blob/master/autoload/rainbow.vim), you have:
```
func rainbow#toggle()
    if exists('g:rainbow_active')
        call rainbow#deactivate()
...
```
So if you set `rainbow_active` to `true` before startup, rainbow is deactivated (?)

**Comment by dbarsam** [comment]
So there was a mix up between the user setting variable and the current state variable.  Got it -- thanks for the fix!

**Comment by dbarsam** [comment]
Re-opening a premature close.

**Pull request merged**
